export const pt = {
    PANUP: "Mover para cima",
    PANDOWN: "Mover para baixo",
    PANLEFT: "Mover para a esquerda",
    PANRIGHT: "Mover para a direita",
    ZOOMIN: "Aumentar zoom",
    ZOOMOUT: "Diminuir zoom",
    TOGGLEZOOM: "Alternar zoom",
    TOGGLE1TO1: "Alternar zoom",
    ITERATEZOOM: "Alternar zoom",
    ROTATECCW: "Rodar no sentido anti-horário",
    ROTATECW: "Rodar no sentido horário",
    FLIPX: "Inverter horizontalmente",
    FLIPY: "Inverter verticalmente",
    FITX: "Ajustar à largura",
    FITY: "Ajustar à altura",
    RESET: "Redefinir",
    TOGGLEFS: "Alternar tela cheia",
    CLOSE: "Fechar",
    NEXT: "Próximo",
    PREV: "Anterior",
    MODAL: "Você pode fechar este conteúdo modal pressionando a tecla ESC",
    ERROR: "Algo deu errado. Por favor, tente novamente mais tarde",
    IMAGE_ERROR: "Imagem não encontrada",
    ELEMENT_NOT_FOUND: "Elemento HTML não encontrado",
    AJAX_NOT_FOUND: "Erro ao carregar AJAX: Não encontrado",
    AJAX_FORBIDDEN: "Erro ao carregar AJAX: Proibido",
    IFRAME_ERROR: "Erro ao carregar página",
    TOGGLE_ZOOM: "Alternar zoom",
    TOGGLE_THUMBS: "Alternar miniaturas",
    TOGGLE_SLIDESHOW: "Alternar apresentação de slides",
    TOGGLE_FULLSCREEN: "Alternar tela cheia",
    DOWNLOAD: "Baixar",
  };
  